# Generated by Django 5.1.1 on 2024-09-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_house_plotofland_delete_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='plotofland',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
