# Generated by Django 5.1.1 on 2024-09-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_house_slug_plotofland_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotofland',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plotofland',
            name='paid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='plotofland',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plotofland',
            name='price',
            field=models.FloatField(max_length=20),
        ),
    ]
