# Generated by Django 5.1.1 on 2024-09-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_plotofland_order_id_plotofland_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='paid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.FloatField(max_length=20),
        ),
    ]
