# Generated by Django 5.1.1 on 2024-09-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_house_order_id_house_paid_house_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='house',
            name='razorpay_payment_id',
        ),
    ]
