# Generated by Django 5.1.1 on 2024-09-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_house_order_id_remove_house_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotofland',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='plotofland',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='plotofland',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='house',
            name='area',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='plotofland',
            name='area',
            field=models.FloatField(default=1),
        ),
    ]
