# Generated by Django 5.1.1 on 2024-09-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_plotofland_order_id_remove_plotofland_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotofland',
            name='area',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='plotofland',
            name='picture1',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='plotofland',
            name='picture2',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='plotofland',
            name='picture3',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='plotofland',
            name='picture4',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
